name: task_list_setstate
description: Task list using StatefulWidget + setState with SQLite + theme toggle
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
flutter:
  uses-material-design: true
